FROM node:22-alpine

# Install pnpm
RUN corepack enable && corepack prepare pnpm@10.6.4 --activate

WORKDIR /app

# Ensure we have the right architecture for binaries (like Prisma or TensorFlow)
RUN apk add --no-cache libc6-compat

# Set pnpm home and store
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN pnpm config set store-dir /pnpm/store

# Ensure dependencies are installed and then start the dev server
CMD ["sh", "-c", "pnpm install && pnpm dev"]
